FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    tesseract-ocr \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir flask pillow pytesseract

COPY simple-ocr-service.py .

EXPOSE 8181

CMD ["python", "simple-ocr-service.py"]
